name: DevOps-frontend
on:
  push:
    branches: ["Don", "Master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Install Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.11.0
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Build Project
        working-directory: ./frontend
        run: npm run build
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4.4.3
        with:
          name: frontend-artifacts
          path: ./frontend/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./frontend/dist
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.CI_CD_TOKEN}}
          publish_dir: './frontend/dist'